### PR TITLE
Clean up prints and add .gitignores

### PR DESCRIPTION
**Pull request by abejgonzalez**
This does small changes to cleanup the prints so that it is a bit more readable/consistent. Additionally, it added `.gitignore` files so that building the KMD/UMD doesn't show untracked files.

### CODE REVIEW

**Comment by abejgonzalez** [comment]
@tymcauley Any thoughts on this?

**Comment by tymcauley** [comment]
> @tymcauley Any thoughts on this?

This look great! I like the idea of replacing most of the `dla_debug` calls with `dla_trace`. You might want to make it clear exactly how to enable `dla_trace`, but I don't really know if this is necessary:

```diff
diff --git a/kmd/firmware/include/dla_debug.h b/kmd/firmware/include/dla_debug.h
index bef99d6..a2ba680 100644
--- a/kmd/firmware/include/dla_debug.h
+++ b/kmd/firmware/include/dla_debug.h
@@ -68,6 +68,7 @@

 #define pr_dump_stack(format, ...)
 #define dla_trace(format, ...)
+// #define dla_trace(format, ...) dla_debug(format, __VA_ARGS__)

 #define assert(condition)
```

While you're cleaning up prints, you might consider this change as well:

```diff
diff --git a/kmd/firmware/engine_debug.c b/kmd/firmware/engine_debug.c
index 7ed4f0a..c9be377 100644
--- a/kmd/firmware/engine_debug.c
+++ b/kmd/firmware/engine_debug.c
@@ -141,6 +141,7 @@ dla_debug_data_cube(struct dla_data_cube *cube)
        dla_debug("    height        = %x\n", cube->height);
        dla_debug("    channel       = %x\n", cube->channel);
        dla_debug("    size          = %u\n", cube->size);
+       dla_debug("    offset        = %u\n", cube->offset);
        dla_debug("    line_stride   = %u\n", cube->line_stride);
        dla_debug("    surf_stride   = %u\n", cube->surf_stride);
        dla_debug("    plane_stride  = %u\n", cube->plane_stride);
```

This is the extra field added to `dla_data_cube` in commit 16befcb84f8ccd2b3d1b0683b965375ae11274df, but it wasn't added to this debug function.

**Comment by abejgonzalez** [comment]
I think I will ignore the extra field added for now mainly because I revert that commit when I want to test regressions (if that field is added, I think it will fail if I just revert that single commit).

**Comment by tymcauley** [comment]
Sounds good! Ya, I was wondering how you ran those regression workloads 🙂

**Pull request merged**
